@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgwOTI3Mjd9.ENqx683_TmMIQN8iwuGESiAdBFGjpoK7rbUcabgiZvg
### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "jason",
  "email": "jason@test.com",
  "password": "password",
  "password_confirmation": "password"
}
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "jason@test.com",
  "password": "password"
}